version: '3.8'

services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - '.:/app'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: npm run dev
    ports:
      - '3000:3000'

  db:
    image: 'docker.io/bitnami/postgresql:15'
    ports:
      - '5432:5432'
    volumes:
      - './postgresql-persistence:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=username
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=blog
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgresql_data:
    driver: local
