version: '3.8'
services:
  database:
    container_name: last-db
    image: 'postgres:15-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: admin
      POSTGRES_DB: posts
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    network_mode: bridge

  frontend:
    container_name: last-frontend
    build:
      context: ./
      target: runner
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
        restart: true
    command: npm run dev
    ports:
      - '3000:3000'

volumes:
  postgresql_data:
    driver: local
